/**
 * Employment-type programmatic pages, extends `/loans/[slug]` with
 * audience pages targeting "personal loan for X" queries by employment type.
 *
 * Same shape as `useCases.ts`.
 */

import type { UseCase } from "@/lib/useCases";

export const employmentTypes: Record<string, UseCase> = {
  "self-employed": {
    slug: "self-employed",
    h1: "Personal loans for self-employed borrowers",
    title: "Personal Loans for Self-Employed Borrowers 2026: How to Qualify",
    description:
      "How self-employed borrowers qualify for personal loans without W-2 income. Documentation requirements, lender expectations, and APR ranges for sole proprietors and small-business owners.",
    eyebrow: "Employment type",
    intro:
      "A personal loan for a self-employed borrower is a standard unsecured installment loan underwritten with self-employment income, typically Schedule C, K-1, or 1099 earnings, instead of W-2 wages. Lenders need additional documentation to verify income, but creditworthy self-employed borrowers can access the full personal-loan market.",
    amountMin: 1000,
    amountMax: 50000,
    termMin: 12,
    termMax: 72,
    aprMin: 6.99,
    aprMax: 35.99,
    bullets: [
      "Sole proprietors, LLC owners, and S-corp owners all qualify",
      "Loan amounts from $1,000 to $50,000",
      "APRs typically 6.99% to 35.99% (credit-dependent)",
      "Typically need 2 years of tax returns to verify income",
      "Strong credit and 2+ years self-employed unlocks the best APRs",
    ],
    faqs: [
      { q: "What income documents do self-employed borrowers need?", a: "Most lenders want two years of personal federal tax returns (Form 1040 with Schedules C, E, and/or K-1). Some accept one year if the business is stable. Recent bank statements (typically 3-6 months) verify cash flow. Newer businesses may need to provide a year-to-date P&L." },
      { q: "How do lenders calculate self-employment income?", a: "Most use a two-year average of net income from your tax returns (Schedule C line 31 for sole proprietors). Some add back depreciation. If income trended down year-over-year, lenders use the more recent (lower) year. If it trended up, the average usually controls." },
      { q: "Can I get a personal loan with less than 2 years of self-employment?", a: "Yes, but options narrow. Some online lenders accept 1 year of self-employment if you have 3+ years of stable W-2 income in the same field beforehand. Strong credit (700+) significantly helps when self-employment history is short." },
      { q: "Should I use gross or net income?", a: "Lenders use net (after-tax-deductible expenses). This can be lower than what you'd report on a W-2 application. Some self-employed borrowers consciously reduce deductions in the year before a major loan application to show higher net income, discuss with a tax pro before doing this." },
    ],
  },
  "1099-contractor": {
    slug: "1099-contractor",
    h1: "Personal loans for 1099 contractors",
    title: "Personal Loans for 1099 Contractors and Freelancers 2026",
    description:
      "Personal loans for 1099 independent contractors: how income is verified, what lenders require, and how to qualify with non-traditional income.",
    eyebrow: "Employment type",
    intro:
      "A personal loan for a 1099 contractor is a standard unsecured installment loan underwritten with independent-contractor income. Lenders weight 1099 earnings similarly to W-2 income once you can document the history and consistency.",
    amountMin: 1000,
    amountMax: 40000,
    termMin: 12,
    termMax: 60,
    aprMin: 7.99,
    aprMax: 35.99,
    bullets: [
      "Full-time and part-time 1099 contractors both qualify",
      "Loan amounts from $1,000 to $40,000",
      "APRs typically 7.99% to 35.99%",
      "Documentation: 2 years of 1099s, tax returns, and recent bank statements",
      "Multiple 1099 income streams can be combined for qualification",
    ],
    faqs: [
      { q: "How do lenders verify 1099 income?", a: "Two main signals: your federal tax returns (showing 1099 income summed on Schedule C or as 'other income') and recent 1099 forms from the payers. Some lenders also want 3-6 months of bank statements to verify the deposits match the reported income." },
      { q: "Is 1099 income treated worse than W-2 income?", a: "Slightly. Lenders see 1099 income as somewhat less stable than W-2 because contracts can end. The discount is usually small for established contractors (2+ years, stable client base), and disappears entirely for borrowers with strong credit." },
      { q: "What if I have both W-2 and 1099 income?", a: "Most lenders will count both. This is the strongest income profile for a contractor, the W-2 portion gives the lender a 'floor' of stable income, and the 1099 piece adds capacity. Bring documentation for both." },
      { q: "Can I get a personal loan if I just started contracting?", a: "Harder, but possible. Strong credit (700+) and a recent strong W-2 history in the same field help significantly. Some lenders accept a single tax year of 1099 income; others want two. Pre-qualification (soft pull) shows you who'll work with you." },
    ],
  },
  "gig-workers": {
    slug: "gig-workers",
    h1: "Personal loans for gig-economy workers",
    title: "Personal Loans for Gig Workers 2026: Uber, DoorDash, Instacart & More",
    description:
      "How rideshare drivers, food-delivery couriers, and other gig workers qualify for personal loans. Income verification, lender expectations, and APR ranges.",
    eyebrow: "Employment type",
    intro:
      "A personal loan for a gig-economy worker is underwritten with platform-earned income (Uber, Lyft, DoorDash, Instacart, Shipt, Amazon Flex, TaskRabbit, etc.) in place of W-2 wages. Lenders need to verify the platform deposits and the history, but established gig workers with stable monthly income can qualify on standard personal-loan terms.",
    amountMin: 500,
    amountMax: 25000,
    termMin: 6,
    termMax: 60,
    aprMin: 12.99,
    aprMax: 35.99,
    bullets: [
      "Income from Uber, DoorDash, Instacart, Shipt, Amazon Flex, TaskRabbit, etc.",
      "Loan amounts from $500 to $25,000",
      "APRs typically 12.99% to 35.99%",
      "Documentation: 1099s from platforms + 3-6 months bank statements",
      "12+ months of gig income with stable monthly deposits unlocks better rates",
    ],
    faqs: [
      { q: "How do lenders verify gig-economy income?", a: "Three signals: 1099-NEC or 1099-K from each platform, recent year's tax return showing the income summed on Schedule C, and 3-6 months of bank statements showing the platform direct deposits. Some lenders also check the in-app earnings dashboards." },
      { q: "Does the lender care which platforms I drive for?", a: "Mostly no. What matters is documented income, not the specific platform. Lenders treat earnings from Uber, Lyft, DoorDash, Instacart, and other established platforms similarly, all are reported on 1099 forms." },
      { q: "Can I get approved with only a few months of gig history?", a: "Approval odds are lower with short history. Most lenders want at least 6 months, and 12+ unlocks the best pricing. If you have a strong recent W-2 history that transitioned to gig work, document the full timeline, lenders often weight that favourably." },
      { q: "Are there lenders that specialise in gig workers?", a: "A handful, typically online installment lenders that explicitly accept platform-deposit verification. Marketplace pre-qualification (soft pull) is the fastest way to see who'll consider you. Don't waste hard inquiries on lenders that exclude gig income." },
    ],
  },
  "w2-employees": {
    slug: "w2-employees",
    h1: "Personal loans for W-2 employees",
    title: "Personal Loans for W-2 Employees 2026: Standard Underwriting Explained",
    description:
      "W-2 employee personal loans: standard documentation, fastest underwriting in the market, and how to qualify for the best APRs at any credit tier.",
    eyebrow: "Employment type",
    intro:
      "A personal loan for a W-2 employee is the standard case in U.S. personal lending. With a regular paycheque, recent W-2 forms, and pay stubs, you have the cleanest possible income documentation, which translates to faster underwriting and broader lender competition for your application.",
    amountMin: 1000,
    amountMax: 50000,
    termMin: 12,
    termMax: 72,
    aprMin: 5.99,
    aprMax: 35.99,
    bullets: [
      "Full-time and part-time W-2 employees qualify",
      "Loan amounts from $1,000 to $50,000",
      "APRs from 5.99% (excellent credit) to 35.99%",
      "Fastest underwriting in the personal-loan market",
      "Standard documentation: recent pay stubs + last year's W-2",
    ],
    faqs: [
      { q: "What documents do W-2 employees need to apply?", a: "Typically 2-3 recent pay stubs, the most recent year's W-2, and government ID. Some lenders also pull bank-statement data via Plaid to verify the deposits. Total documentation usually takes 5-10 minutes to gather." },
      { q: "How long does W-2 underwriting take?", a: "Often minutes. Online lenders pull credit, verify employment and income against the documents you upload, and decision in real time. Funding typically lands the next business day after acceptance." },
      { q: "Can part-time W-2 income qualify me?", a: "Yes. Lenders look at total monthly income and debt-to-income ratio, not whether you're full or part time. Part-time income from a long-tenured job is treated similarly to full-time income from the same employer." },
      { q: "What if I just started a new W-2 job?", a: "Most lenders want at least 30-90 days at the new employer plus a prior history in the same field. Job-hopping within an industry is usually fine; switching industries can require longer recent tenure. An offer letter alone usually isn't enough for approval before the first paycheque clears." },
    ],
  },
  "seasonal": {
    slug: "seasonal",
    h1: "Personal loans for seasonal workers",
    title: "Personal Loans for Seasonal Workers 2026: Variable Income, Year-Round Repayment",
    description:
      "How seasonal workers qualify for personal loans on irregular income. Tax returns, bank statements, and documentation strategies for agriculture, tourism, and construction workers.",
    eyebrow: "Employment type",
    intro:
      "Seasonal workers, including those in agriculture, construction, landscaping, hospitality, tourism, and retail holiday staffing, earn most of their income in specific months but face year-round expenses. Personal loan underwriters care about average annual income, not whether it arrives in peaks. With 2 years of tax returns showing consistent seasonal earnings, most mainstream lenders will underwrite seasonal income the same as regular income.",
    amountMin: 500,
    amountMax: 30000,
    termMin: 12,
    termMax: 60,
    aprMin: 9.99,
    aprMax: 35.99,
    bullets: [
      "2 years of tax returns documents consistent seasonal income",
      "Annual gross income used for DTI, not monthly peaks",
      "Loan amounts from $500 to $30,000",
      "APRs 9.99% to 35.99% depending on credit",
      "Soft credit check to compare, no score impact",
    ],
    faqs: [
      { q: "How do seasonal workers document income for a personal loan?", a: "Two years of tax returns (Schedule C for self-employed seasonal workers, W-2s for seasonal employees) are the primary income documentation. Lenders calculate 24-month average annual income and divide by 12 for a monthly income figure. Bank statements showing seasonal income deposits (6-12 months of highs with periodic gaps) help tell the story of your income pattern." },
      { q: "Can I get a personal loan during my off-season?", a: "Yes, if your annual income supports it. Lenders look at your full-year income pattern, not just what you're earning at the moment of application. A construction worker earning $65,000 between April and November who applies in January can qualify using the prior year's income. Off-season applications require strong bank account reserves or evidence that the seasonal employment is returning." },
      { q: "Are credit unions better for seasonal workers?", a: "Often yes. Credit unions with ties to specific industries (agriculture credit unions, teachers' credit unions, etc.) understand seasonal income patterns better than algorithmic online lenders. If you belong to an industry-specific credit union, this is the best first stop for a personal loan. They may be willing to count seasonal income more generously than a national online lender." },
      { q: "What if this is my first year of seasonal work?", a: "One year of seasonal income history is a challenge for most lenders who want 2+ years. Options include applying with a co-borrower who has stable income, using a secured personal loan backed by savings, or targeting lenders known for flexible employment verification (some fintechs use bank data rather than tax returns and can see real income even without 2-year history)." },
    ],
  },
  "healthcare-workers": {
    slug: "healthcare-workers",
    h1: "Personal loans for healthcare workers",
    title: "Personal Loans for Healthcare Workers 2026: Nurses, RNs, Doctors & Medical Staff",
    description:
      "Personal loans for nurses, registered nurses, doctors, and healthcare staff. Licensing, shift pay, and travel nursing income all qualify. APR ranges and documentation.",
    eyebrow: "Employment type",
    intro:
      "Healthcare workers, including registered nurses, nurse practitioners, physicians, medical assistants, and allied health professionals, often have strong income but complex pay structures: shift differentials, overtime, PRN (per diem) pay, travel nursing stipends, and sign-on bonuses. Most lenders can accommodate healthcare income with standard pay-stub documentation. Travel nurses and PRN workers need bank-statement income history to document variable pay.",
    amountMin: 1000,
    amountMax: 50000,
    termMin: 12,
    termMax: 72,
    aprMin: 7.99,
    aprMax: 29.99,
    bullets: [
      "Shift differentials and overtime count as qualifying income",
      "Travel nursing stipends may count at some lenders",
      "Loan amounts from $1,000 to $50,000",
      "APRs 7.99% to 29.99% depending on credit",
      "Soft credit check pre-qualification, no score impact",
    ],
    faqs: [
      { q: "Do travel nursing stipends count as income for a personal loan?", a: "It varies by lender. Travel nursing compensation includes a taxable base pay plus non-taxable housing and meal stipends. Most lenders only count taxable wages shown on pay stubs for qualification, not the non-taxable stipends. Some lenders that specialize in healthcare workers will count total package compensation. Bank statements showing actual deposits are helpful supplemental documentation for the full income picture." },
      { q: "Can I include nursing overtime when applying for a personal loan?", a: "Yes, if it's consistent. Most lenders will count overtime that appears regularly (consistently for 12-24 months) in your income calculation. Occasional overtime is usually not counted. Bring 2-3 recent pay stubs plus a year or two of W-2s that show overtime history to document consistent additional income." },
      { q: "Are there personal loans specifically for nurses?", a: "Some lenders and credit unions market nurse-specific loan programs with slightly relaxed qualification criteria or lower APRs. Laurel Road (which has historically served healthcare professionals), SoFi, and some healthcare credit unions (like Healthcare Financial Federal Credit Union, Nurses Financial) have featured nurse-focused products. Availability and terms change frequently; compare these alongside mainstream marketplace lenders for the best rate." },
      { q: "I'm a PRN (per diem) nurse. Can I qualify?", a: "Yes, with appropriate documentation. PRN nurses have variable income that fluctuates week to week. The key is documenting 12-24 months of consistent PRN income. Bank statements showing regular deposits, tax returns, and a letter from your staffing agency confirming your rates and availability can support your application. Credit unions familiar with healthcare employment are more likely to underwrite PRN income favorably than algorithmic online lenders." },
    ],
  },
  "part-time": {
    slug: "part-time",
    h1: "Personal loans for part-time workers",
    title: "Personal Loans for Part-Time Workers 2026: Qualify on Variable Income",
    description:
      "How part-time workers get personal loan approval: income documentation, lender requirements, and APRs available on part-time or variable income.",
    eyebrow: "Employment type",
    intro:
      "Part-time workers can qualify for personal loans using the same underwriting as full-time employees. Lenders care about total monthly income and DTI ratio, not the number of hours worked. A part-time worker earning $2,500/month with low existing debt can qualify for the same loan amount as a full-time worker with identical numbers. The key is documenting income consistently.",
    amountMin: 500,
    amountMax: 25000,
    termMin: 12,
    termMax: 60,
    aprMin: 9.99,
    aprMax: 35.99,
    bullets: [
      "Part-time income qualifies the same as full-time at most lenders",
      "Loan amounts from $500 to $25,000 based on income",
      "APRs typically 9.99% to 35.99% depending on credit",
      "2-3 recent pay stubs or bank statements document income",
      "Soft credit check, no score impact to compare offers",
    ],
    faqs: [
      { q: "Can I get a personal loan working part time?", a: "Yes. Lenders don't require full-time status; they require verifiable income and a DTI ratio that supports the loan payment. If your part-time income is consistent and documented (pay stubs, bank statements, or 1099s), you can qualify for a personal loan the same way a full-time employee would." },
      { q: "How do I document part-time income for a loan application?", a: "Two to three recent pay stubs work for W-2 part-time work. For part-time contract or freelance work, 3 months of bank statements showing recurring income deposits is the most accepted alternative. Some lenders also accept a letter from your employer confirming pay rate and schedule." },
      { q: "Will multiple part-time jobs count together?", a: "Yes at most lenders. If you hold multiple part-time jobs, you can typically report combined income from all sources. You'll need documentation for each income stream. Lenders generally want to see income from each source for at least 2-6 months before counting it." },
      { q: "What's the maximum loan amount on part-time income?", a: "It depends on total monthly income and existing debt. On $2,000/month part-time income with minimal debt, a $10,000 loan over 36 months at 18% APR results in a $363 payment, which is 18% of gross monthly income (well within lender guidelines). On $3,000/month income, you can support a proportionally larger loan." },
    ],
  },
  "retired": {
    slug: "retired",
    h1: "Personal loans for retired people",
    title: "Personal Loans for Retired Borrowers 2026: Social Security, Pension & Fixed Income",
    description:
      "How retirees qualify for personal loans using Social Security, pension, IRA distributions, and fixed income. APRs, amounts, and documentation requirements.",
    eyebrow: "Employment type",
    intro:
      "Retirement income, including Social Security, pension payments, IRA/401(k) distributions, and investment income, counts the same as earned income for personal loan purposes under ECOA. Lenders may not discriminate based on age or income source. A retired borrower with consistent documented income and a good credit score can access the same loan amounts and APRs as a working borrower with equivalent numbers.",
    amountMin: 1000,
    amountMax: 40000,
    termMin: 12,
    termMax: 60,
    aprMin: 7.99,
    aprMax: 29.99,
    bullets: [
      "Social Security, pension, and IRA income fully counts",
      "ECOA prohibits age discrimination in lending",
      "Loan amounts from $1,000 to $40,000",
      "APRs typically 7.99% to 29.99% based on credit",
      "Soft credit check pre-qualification, no score impact",
    ],
    faqs: [
      { q: "Can retired people get personal loans?", a: "Yes. The Equal Credit Opportunity Act prohibits lenders from discriminating based on age. Retirement income (Social Security, pension, IRA/401k distributions, rental income, investment income) counts as qualifying income the same as wages. A retiree with $4,000/month in documented retirement income and a 720 credit score is a strong applicant." },
      { q: "What income counts for retired borrowers?", a: "Social Security retirement benefits, pension payments (public or private), regular IRA or 401(k) distributions, annuity payments, rental income, and investment dividend income all count. The income should be regular (monthly or at set intervals) and documentable. Social Security award letters and 1099-R forms are the standard proof documents." },
      { q: "Does my age affect my loan term options?", a: "Legally, no. Lenders cannot shorten your available loan term based on age. The same 60-month or 72-month personal loan terms available to younger borrowers must be offered to older borrowers with equivalent credit. Some retirees prefer shorter terms to minimize total interest; this is a personal choice, not a lender requirement." },
      { q: "How do I document retirement income?", a: "Social Security: use your annual SSA benefit verification letter or SSA-1099. Pension: pension award letter or 1099-R from the payer. IRA/401(k) distributions: 1099-R plus recent distribution statements. Consistent bank statements showing deposits also work as supplemental documentation at most lenders." },
    ],
  },
  "military": {
    slug: "military",
    h1: "Personal loans for military members and veterans",
    title: "Personal Loans for Military & Veterans 2026: MLA Protections, APR Cap & Options",
    description:
      "Personal loans for active-duty military and veterans: 36% MLA APR cap, SCRA protections, VA loan alternatives, and lenders that specialize in military borrowers.",
    eyebrow: "Employment type",
    intro:
      "Active-duty service members and their dependents have two important federal protections: the Military Lending Act (MLA) caps consumer loan APRs at 36% MAPR, and the Servicemembers Civil Relief Act (SCRA) caps interest on pre-service debts at 6%. Veterans without active-duty status have the same access as civilians but can benefit from military-affiliated credit unions (USAA, Navy Federal, PenFed) that often offer lower APRs and better underwriting for military income.",
    amountMin: 500,
    amountMax: 50000,
    termMin: 12,
    termMax: 84,
    aprMin: 5.99,
    aprMax: 35.99,
    bullets: [
      "MLA caps APR at 36% for active-duty members and dependents",
      "Military credit unions often offer lowest personal loan APRs",
      "Loan amounts from $500 to $50,000",
      "VA income (BAH, BAS) counts toward qualifying income",
      "Soft credit check pre-qualification available",
    ],
    faqs: [
      { q: "What is the MLA and how does it protect military borrowers?", a: "The Military Lending Act caps the Military Annual Percentage Rate (MAPR, which includes fees) at 36% for personal loans to active-duty service members, spouses, and certain dependents. Lenders must disclose this rate and certain loan terms orally and in writing. A lender offering a product that would exceed 36% MAPR to a covered borrower is violating federal law." },
      { q: "Do military credit unions offer better personal loan rates?", a: "Often significantly better. Navy Federal Credit Union, USAA Federal Savings Bank, and Pentagon Federal Credit Union regularly offer personal loan APRs starting around 7-8% for members with good credit, well below what most online lenders offer to the same credit profile. If you or an immediate family member have ever served, membership eligibility is worth checking." },
      { q: "Does military pay (BAH, BAS) count as qualifying income?", a: "Yes. Base pay, Basic Allowance for Housing (BAH), and Basic Allowance for Subsistence (BAS) all count as qualifying income for personal loans. These allowances are non-taxable, so lenders that 'gross up' non-taxable income may apply a 25-35% adjustment upward to the allowance figure, effectively increasing your qualifying income." },
      { q: "Can veterans (not active duty) access military loan protections?", a: "Veterans after discharge are not covered by MLA protections (which apply only during active duty to covered borrowers). However, veterans retain access to military-affiliated credit unions with favorable terms and strong service. Some lenders also have veteran-specific programs. SCRA protections apply only during active service for pre-service debts." },
    ],
  },
  "commission-based": {
    slug: "commission-based",
    h1: "Personal loans for commission-based workers",
    title: "Personal Loans for Commission-Based Workers 2026: Variable Income Qualification Guide",
    description:
      "Sales reps, real estate agents, and other commission earners can qualify for personal loans. Here is how lenders verify irregular income, what documents you need, and the APR ranges to expect.",
    eyebrow: "Employment type",
    intro:
      "Commission-based workers - real estate agents, sales representatives, independent insurance agents, financial advisors, and others with variable monthly income - can qualify for personal loans. The underwriting challenge is proving reliable average income when no two paychecks are the same. Most lenders use a 12-24 month average of documented commissions rather than a recent month's earnings.",
    amountMin: 1000,
    amountMax: 50000,
    termMin: 12,
    termMax: 72,
    aprMin: 7.99,
    aprMax: 35.99,
    bullets: [
      "Lenders average your last 12-24 months of documented commission income",
      "Loan amounts from $1,000 to $50,000",
      "APRs typically 7.99%-35.99% based on credit score and income stability",
      "Two years of tax returns (Schedule C or W-2 with commissions) typically required",
      "Soft credit check pre-qualification available at most online lenders",
    ],
    faqs: [
      { q: "How do lenders verify commission income?", a: "Most lenders require 1-2 years of federal tax returns (Schedule C for self-employed or W-2 plus commission statements for employees), recent bank statements showing the deposits, and sometimes a signed letter from your employer confirming the commission structure. Lenders will typically average the total annual commission over the past 12-24 months and divide by 12 to arrive at a monthly income figure. If your income has been growing, some lenders will weight more recent income more heavily." },
      { q: "What if my commission income is irregular month-to-month?", a: "This is expected for commission earners, and lenders account for it. The averaging approach (total commissions over 24 months divided by 24) smooths out the peaks and valleys. However, if your current year's income is significantly lower than prior years (for example, during a real estate market slowdown), lenders may use the current year or discount prior years. Providing a written explanation of your income trajectory and the nature of your business can help." },
      { q: "Do lenders distinguish between W-2 commission employees and independent contractors?", a: "Yes. W-2 commission employees (common in corporate sales jobs) have more predictable documentation - W-2 forms and employer-provided commission statements. Independent contractors (1099 income) are treated more like self-employed borrowers and typically need to provide Schedule C filings and business bank statements. The income averaging principle is the same, but independent contractors face additional scrutiny on business expenses and net income versus gross commissions." },
      { q: "Will a lender count a recent big commission month toward my income?", a: "Generally no. One standout month does not move the qualifying income number much when lenders are averaging 12-24 months. The flip side is also true: one bad month has limited impact. Lenders are looking for the sustainable trend, not the peak. If you recently closed an unusually large deal, note it in your application but expect qualifying income to be based on the multi-year average." },
    ],
  },
  "small-business-owners": {
    slug: "small-business-owners",
    h1: "Personal loans for small business owners",
    title: "Personal Loans for Small Business Owners 2026: Qualification Guide",
    description:
      "Small business owners can use personal loans for business or personal needs. Learn how lenders evaluate business income, what documents are required, and when a personal loan beats a business loan.",
    eyebrow: "Employment type",
    intro:
      "Small business owners who take owner distributions, pay themselves a salary, or report business income on personal tax returns can qualify for personal loans. Lenders evaluate the business's net income (after expenses) rather than gross revenue, which can create challenges when business deductions are aggressive. This guide explains how to position your income for approval.",
    amountMin: 2000,
    amountMax: 100000,
    termMin: 12,
    termMax: 84,
    aprMin: 7.99,
    aprMax: 29.99,
    bullets: [
      "Net business income (Schedule C) used for qualifying, not gross revenue",
      "Two years of personal and business tax returns typically required",
      "Loan amounts from $2,000 to $100,000 depending on lender",
      "Faster and simpler than an SBA loan for amounts under $50,000",
      "Soft credit check pre-qualification available at most online lenders",
    ],
    faqs: [
      { q: "Will a lender care that the loan is for my business if I apply personally?", a: "Most personal loan lenders do not restrict the use of unsecured loan proceeds and do not ask whether you plan to use funds for personal or business purposes. A small business owner can apply for a personal loan and use the funds for business inventory, equipment, cash flow, or any other purpose. If you tell the lender the purpose is 'business,' some lenders may redirect you to a business loan product. The loan remains a personal loan with personal liability regardless of how you use it." },
      { q: "Do I need to provide business tax returns in addition to personal returns?", a: "Often yes. If you are a sole proprietor filing Schedule C, your personal and business returns are combined on your Form 1040. If you own an S-corp or partnership, lenders typically want 2 years of business returns (Form 1120S or 1065) plus your personal return to see your K-1 income. Lenders want to verify the business is profitable and that your owner income is sustainable." },
      { q: "My business had a bad year - will that disqualify me?", a: "One bad year is manageable if the prior year was strong and you can explain the circumstance (market conditions, a one-time expense). Lenders that use a 2-year income average will smooth out one weak year. If two consecutive years show declining net income, approval becomes harder. In that case, consider a co-borrower with stable W-2 income or apply for a smaller loan amount with more manageable payments." },
      { q: "Is a personal loan or a business loan better for my small business?", a: "For amounts under $50,000 and when you need funds quickly, a personal loan is typically faster and simpler. Business loans (SBA 7(a), bank term loans) offer higher amounts, longer terms, and business credit building, but require more documentation, longer timelines (weeks to months), and often collateral. Personal loans do not build business credit but fund in 1-3 days. For working capital or equipment under $50,000 on a short timeline, a personal loan usually wins on speed. For growth capital over $100,000, a business loan is the appropriate tool." },
    ],
  },
  "recent-graduates": {
    slug: "recent-graduates",
    h1: "Personal loans for recent college graduates",
    title: "Personal Loans for Recent College Graduates 2026: Building Credit While Borrowing",
    description:
      "Recent graduates often have limited credit history but real income. Learn how to qualify for a personal loan right after college, what rates to expect, and how borrowing responsibly builds the credit profile you will need for the next decade.",
    eyebrow: "Employment type",
    intro:
      "Recent college graduates face a common credit paradox: they have a degree, a new job, and income - but little credit history to show lenders. This thin-file problem means most graduates start with a moderate credit score (580-680) and pay higher rates than their income would otherwise suggest. The good news: a responsibly managed personal loan is one of the fastest tools for building the credit history that unlocks better rates going forward.",
    amountMin: 1000,
    amountMax: 25000,
    termMin: 12,
    termMax: 60,
    aprMin: 10.99,
    aprMax: 29.99,
    bullets: [
      "Thin credit history is the primary obstacle, not income",
      "A co-signer from a parent can dramatically improve approval odds and rate",
      "Loan amounts from $1,000 to $25,000 depending on income and credit score",
      "On-time repayment rapidly builds credit history for future borrowing",
      "Soft credit check pre-qualification available with no score impact",
    ],
    faqs: [
      { q: "What credit score does a recent graduate typically have?", a: "Many new graduates have scores in the 580-680 range if they have had a credit card for 1-4 years. Graduates with no credit history at all may have no score (unscoreable) or a thin-file score. Scores in the 580-680 range are sufficient for approval at near-prime lenders such as Avant, Upgrade, and LendingClub, but will result in higher interest rates, typically 15%-28% APR. A co-signer with a 720+ credit score dramatically improves both approval odds and the rate offered." },
      { q: "Can I use my new job offer letter to qualify before I have a paycheck?", a: "Yes, many lenders accept a signed offer letter as proof of income for applications within 30-90 days of a start date. Include the letter, start date, and annual salary clearly. Call the lender to confirm they accept offer letters before applying. Upgrade, SoFi, and several credit unions explicitly allow this. Once you receive your first paycheck, the process becomes more straightforward." },
      { q: "Should I use a personal loan to pay off my student loans?", a: "This is rarely advisable. Federal student loans come with income-based repayment options, forgiveness programs (PSLF, IDR), deferment, and forbearance options that a personal loan does not provide. Refinancing federal loans into a personal loan permanently eliminates those protections. For private student loans at high rates, refinancing into a personal loan is worth calculating if the personal loan rate is materially lower. But do not refinance federal loans with a personal loan." },
      { q: "How does taking a personal loan now help my credit later?", a: "Payment history (35% of your FICO score) is built over time by making consistent on-time payments. An installment loan also improves your credit mix, showing you can manage both revolving credit (credit cards) and installment accounts (loans). A 24-month personal loan repaid on time adds 24 months of positive installment history to your credit report. This builds the track record that future lenders will review when you apply for an auto loan, mortgage, or larger personal loan." },
    ],
  },

  "teachers": {
    slug: "teachers",
    eyebrow: "Employment type",
    h1: "Personal loans for teachers and educators (2026)",
    title: "Personal Loans for Teachers 2026: Rates, Amounts & Lenders",
    description:
      "Personal loan options for teachers, school administrators, and public education employees. APRs from 7.99% to 24.99% and amounts from $2,000 to $50,000.",
    intro:
      "Teachers and education professionals have stable, documented income that most lenders view favorably. School district employment typically means predictable annual salary, year-round (or 10-month) pay schedules, and strong job security - all positive factors for loan approval. Whether you need funds for classroom supplies, summer gap coverage, continuing education, home improvement, or debt consolidation, personal loans offer a flexible solution.",
    amountMin: 2000,
    amountMax: 50000,
    termMin: 12,
    termMax: 84,
    aprMin: 7.99,
    aprMax: 24.99,
    bullets: [
      "Stable school district income viewed favorably by lenders",
      "APRs typically 7.99% to 24.99% depending on credit score",
      "Loan amounts from $2,000 to $50,000",
      "10-month pay schedule borrowers: lenders use annual income, not just in-school months",
      "Soft credit check pre-qualification available",
    ],
    faqs: [
      { q: "How do lenders handle the 10-month school pay schedule?", a: "Lenders use annual income, not monthly income from the school calendar. If you earn $52,000/year paid over 10 months ($5,200/month during the school year), lenders calculate your monthly income as $52,000 divided by 12 = $4,333 for DTI purposes. This is standard practice. If your pay stubs only show 10 months of salary, provide your employment contract or a letter from HR showing your annual salary." },
      { q: "Are there loan programs specifically for teachers?", a: "A handful of credit unions and community banks offer teacher-specific products with preferred rates or fees, especially those associated with school district employees (like education credit unions). Nationwide, some lenders advertise 'teacher loans' but these are standard personal loans with marketing. The more impactful benefit for teachers is that school district employment - government employer, stable income, pension - signals low risk to lenders, which improves your rate even at standard lenders." },
      { q: "Can a teacher get a personal loan during the summer without a current paycheck?", a: "Yes - income is verified at application time, not monthly. When you apply in June, lenders verify your annual salary from your most recent pay stubs, W-2, or employment contract. Most lenders do not re-verify income monthly. Approval is based on annual income and DTI, not whether you currently have an active paycheck. Payments will still be due during summer, so plan your budget around meeting payments from savings during the non-pay period." },
      { q: "Can I use a personal loan for classroom supplies?", a: "Yes - personal loans can be used for any purpose, including classroom supplies. Separately, teachers can deduct up to $300 per year (federal Educator Expense Deduction) for out-of-pocket classroom expenses. This deduction applies to the underlying expense, not to loan interest. Personal loan interest is not tax-deductible for consumer purposes. The $300 educator deduction is an above-the-line deduction regardless of whether you itemize." },
    ],
  },

  "disability-recipients": {
    slug: "disability-recipients",
    eyebrow: "Employment type",
    h1: "Personal loans for disability recipients (SSDI and SSI, 2026)",
    title: "Personal Loans for Disability Recipients 2026: SSDI & SSI Options",
    description:
      "Personal loan options for recipients of SSDI and SSI disability benefits. Amounts from $500 to $20,000 and lenders that count disability income for qualification.",
    intro:
      "Disability income - whether SSDI, SSI, VA disability benefits, or long-term disability insurance - is recognized as qualifying income by personal loan lenders under the Equal Credit Opportunity Act. You cannot be denied or offered worse terms solely because your income comes from disability benefits. The key factors are the same as for any borrower: income amount, credit score, and existing debt obligations.",
    amountMin: 500,
    amountMax: 20000,
    termMin: 12,
    termMax: 60,
    aprMin: 10.99,
    aprMax: 35.99,
    bullets: [
      "SSDI, SSI, VA disability, and long-term disability all count as qualifying income",
      "ECOA prohibits lenders from discounting or denying based on disability income source",
      "Loan amounts from $500 to $20,000 depending on monthly benefit and credit score",
      "Documentation: SSA benefit verification letter or VA award letter",
      "Soft credit check pre-qualification with no score impact",
    ],
    faqs: [
      { q: "What documentation does a disability recipient need to apply?", a: "For SSDI or SSI: an SSA Benefit Verification Letter, available at ssa.gov/myaccount or by calling 1-800-772-1213. The letter shows your current monthly benefit amount. For VA disability: your VA Rating Decision letter showing your combined disability rating and monthly payment. For private long-term disability: the benefit award letter from the insurance carrier. Have recent bank statements available to show the deposits arriving regularly." },
      { q: "Can I get a personal loan if SSI is my only income?", a: "SSI (Supplemental Security Income) is means-tested for low-income individuals with disabilities. The maximum federal SSI benefit in 2026 is approximately $967/month for an individual. At this income level, qualifying for a meaningful loan is difficult: $967/month supports approximately $240-$290/month in total debt payments at 25%-30% DTI, limiting eligibility to amounts around $2,000-$5,000. SSDI recipients with higher monthly benefits (average SSDI in 2026 is approximately $1,580/month) have more options." },
      { q: "Will the loan affect my disability benefits?", a: "For SSDI recipients: No. SSDI has no asset limit, and loan proceeds are not considered income under SSDI rules. For SSI recipients: SSI has a $2,000 asset limit ($3,000 for couples). Holding loan proceeds in a bank account above that limit could affect your SSI eligibility for that month. Spend loan funds in the same month received, or consult a WIPA benefits counselor (Work Incentive Planning and Assistance, available free through SSA) before borrowing." },
    ],
  },
  "nurses": {
    slug: "nurses",
    h1: "Personal Loans for Nurses",
    title: "Personal Loans for Nurses (2026): Best Rates & Lenders for RNs and LPNs",
    description: "Nurses are among the most creditworthy borrowers due to stable, high-demand income. Compare the best personal loan rates and lenders for RNs, LPNs, CRNAs, and travel nurses in 2026.",
    eyebrow: "Employment type",
    intro: "Registered nurses and licensed practical nurses combine high income stability with strong job security - two factors personal loan lenders weight heavily. Hospital and health system nurses earn $65,000-$140,000 annually depending on specialty and market, making them attractive borrowers who qualify for prime rates. Travel nurses require additional documentation but can still access competitive loan products.",
    amountMin: 1000,
    amountMax: 75000,
    termMin: 12,
    termMax: 84,
    aprMin: 7.49,
    aprMax: 21.99,
    bullets: [
      "RN median income of ~$82,000 nationally qualifies for lender best-rate tiers",
      "W-2 hospital employment is the strongest income profile for personal loan approval",
      "Travel nurses need 2+ years 1099 history or employer W-2 through a staffing agency",
      "Nurse-specific credit unions (Healthcare Employees CU, regional hospital CUs) offer member discounts",
      "Specialty nurses (CRNAs, NPs) earning over $120,000 often qualify for LightStream's lowest rates",
    ],
    faqs: [
      { q: "Do lenders verify that I am a nurse when I apply?", a: "Lenders verify income and employment, not your professional license. They will confirm employment with your hospital, health system, or staffing agency and verify your income via pay stubs, W-2s, or bank statements. Your nursing license is not typically checked as part of the loan application. However, your employer confirmation call or online employment verification will confirm your job title, which will show 'registered nurse' or equivalent. Falsifying your employment or income on a loan application is a federal crime under 18 U.S.C. 1014." },
      { q: "How do travel nurses qualify for a personal loan?", a: "Travel nurses are typically employed by a staffing agency on 13-week contracts. Most travel nurses receive W-2 income through the staffing agency, which makes them employed workers (not self-employed) in the eyes of lenders. To qualify: provide 2 years of W-2s from nursing employment (travel or permanent), recent pay stubs from your current assignment, and a letter from the staffing agency or current hospital confirming active assignment. Some lenders also look at bank statements showing regular direct deposits. A brief gap between contracts (1-4 weeks) does not typically disqualify you as long as your annual income history is consistent." },
      { q: "Can a nursing student get a personal loan?", a: "A nursing student can apply for a personal loan based on any other income they have (part-time work, scholarships do not count as income, but paid clinical stipends or work-study wages do). Most nursing students do not qualify for significant personal loan amounts without co-signer support because income is typically low during school. Better options for nursing students: federal nursing student loans through FAFSA (Nurse Faculty Loan Program, NHSC Loan Repayment), private student loans specifically for healthcare programs (from Sallie Mae, College Ave), or a co-signed personal loan if a parent or spouse has qualifying income and credit." },
    ],
  },
  "restaurant-workers": {
    slug: "restaurant-workers",
    h1: "Personal Loans for Restaurant Workers",
    title: "Personal Loans for Restaurant Workers (2026): Tips, Tipped Income & Approval",
    description: "Restaurant workers, servers, bartenders, and cooks face unique challenges qualifying for personal loans due to variable and tip-based income. See which lenders work best and how to document tipped income in 2026.",
    eyebrow: "Employment type",
    intro: "Restaurant workers - servers, bartenders, line cooks, kitchen managers, and front-of-house staff - often earn substantial income that is partially or fully tip-based. This creates income documentation challenges that can complicate personal loan applications. With the right preparation and lender selection, restaurant workers can access personal loans at competitive rates.",
    amountMin: 500,
    amountMax: 30000,
    termMin: 12,
    termMax: 60,
    aprMin: 10.99,
    aprMax: 29.99,
    bullets: [
      "Tip income declared on tax returns counts as qualifying income for most lenders",
      "Bank statements showing consistent deposits can substitute when pay stubs understate tips",
      "Restaurant managers and salaried kitchen staff qualify the same as any W-2 employee",
      "Lenders using Plaid or bank account data can see total deposit history, capturing undeclared tips",
      "Credit unions in hospitality-heavy markets often have more experience with tipped-income borrowers",
    ],
    faqs: [
      { q: "How do I prove my tip income when applying for a personal loan?", a: "The most credible documentation for tip income: (1) Tax returns (Schedule 1 or W-2 showing allocated tips) - the gold standard because it is IRS-verified. (2) Bank statements from the last 3-6 months showing regular deposits consistent with your stated income level. (3) Employer tip records or tip tracking app history. (4) Some lenders use Plaid or similar bank data aggregators that see actual deposits directly - if your tips are deposited to your checking account (even informally), this data supports your stated income. Undeclared tips that never appear in any verifiable record cannot be included in your stated income without documentation risk." },
      { q: "What if my W-2 income is low but my tips are high?", a: "If your W-2 shows only your $15,000 base wage but you actually earn $45,000 with tips, the W-2 alone will make you look underqualified. Options: (1) Use your full tax return (which should show declared tips on Form 4137 or employer-allocated tip reporting). (2) Use bank statements that show your actual deposit amounts over 6-12 months. (3) Apply with a lender that accepts bank statement underwriting (Upgrade, some credit unions) rather than requiring W-2-only income verification. (4) Increase your declared tip income via Form 4137 on future taxes (this is also legally required if your unreported tips exceed $20/month). (5) Apply jointly with a household member who has W-2 income." },
      { q: "Can seasonal restaurant workers get a personal loan during the off-season?", a: "Seasonal restaurant workers (ski resort, beach resort, summer festival) with very low or no income in the off-season face real qualification challenges. Strategies: (1) Apply at the peak of your season when recent pay stubs show high income. Most lenders look at the most recent 2-3 months of income. (2) Use annualized income from tax returns (if consistent year to year) to show your typical annual earnings. (3) Apply with a credit union or community bank familiar with your market's seasonal patterns. (4) Have a co-signer with year-round income. Unemployment benefits typically count as qualifying income during off-season if you collect them." },
    ],
  },
  "federal-employees": {
    slug: "federal-employees",
    h1: "Personal Loans for Federal Government Employees",
    title: "Personal Loans for Federal Employees (2026): Best Rates & Lenders",
    description: "Federal employees get some of the best personal loan rates due to stable income and job security. Compare lenders, allotment loan options, and TSP alternatives for 2026.",
    eyebrow: "Employment type",
    intro: "Federal government employees - including civilian workers for the DoD, VA, USDA, IRS, and other agencies - are among the most creditworthy borrowers in the personal loan market. Stable W-2 income, civil service protections that limit termination, and access to allotment repayment (automatic deduction from paycheck) give lenders high confidence in repayment. Federal employees typically access some of the lowest APRs in the personal loan market.",
    amountMin: 1000,
    amountMax: 100000,
    termMin: 12,
    termMax: 84,
    aprMin: 6.99,
    aprMax: 19.99,
    bullets: [
      "Federal job security makes you a low default-risk borrower - lenders compete for your business",
      "Allotment loans repay automatically from your federal paycheck via payroll deduction",
      "Navy Federal Credit Union (open to federal employees) offers rates as low as 7.49%",
      "TSP loan (Thrift Savings Plan) is a 0% collateral alternative - but reduces retirement savings",
      "LightStream regularly offers sub-8% APR to federal workers with strong credit",
    ],
    faqs: [
      { q: "What is an allotment loan for federal employees?", a: "An allotment loan is a personal loan repaid via payroll deduction directly from your federal paycheck before you receive it. The lender receives payment automatically on payday, eliminating missed payments. Several lenders specialize in federal employee allotment loans, including Kashable (available through some federal agencies as a workplace benefit) and a number of credit unions serving federal workers. Allotment loans often carry lower rates (12%-18%) than equivalent personal loans because the automatic repayment mechanism nearly eliminates default risk. To get an allotment loan, your agency must participate in the allotment program." },
      { q: "Should I take a TSP loan or a personal loan?", a: "A TSP loan (Thrift Savings Plan loan) lets federal employees borrow from their own retirement savings at the G Fund rate (currently around 4%-5%) and repay via payroll deduction. It sounds attractive, but the true cost is higher than the interest rate: while your money is out of the TSP, it is not earning market returns. Over a 5-year loan during a bull market, the missed compounding can cost far more than 4%-5%. A personal loan from LightStream or Navy Federal at 7%-10% APR leaves your TSP growing. Only use a TSP loan if: you cannot qualify for a personal loan, the TSP rate is significantly below current personal loan rates, or you need funds urgently and a personal loan cannot fund in time." },
      { q: "Which credit union offers the best rates for federal employees?", a: "Several credit unions serve federal employees with excellent rates: (1) Navy Federal Credit Union - open to DoD employees, veterans, and their families. Personal loan rates start at 7.49% with no origination fees. (2) Pentagon Federal Credit Union (PenFed) - open to federal employees and military. Personal loan rates starting around 7.99%-8.99% for strong credit. (3) First Tech Federal Credit Union - serves employees of tech companies and federal credit union members. Competitive rates for government contractors. (4) Your agency may have a dedicated credit union (State Department FCU, NASA FCU, etc.) with even lower rates. Check with your agency's HR office for affiliated credit union options." },
    ],
  },
  "first-responders": {
    slug: "first-responders",
    h1: "Personal Loans for First Responders",
    title: "Personal Loans for First Responders (2026): Firefighters, Police & EMTs",
    description: "First responders including firefighters, police officers, and EMTs qualify for specialized personal loan rates and programs. Compare your best options in 2026.",
    eyebrow: "Employment type",
    intro: "Firefighters, police officers, sheriff's deputies, EMTs, and paramedics - collectively called first responders - are public servants with stable government incomes and strong community bank and credit union relationships. Many financial institutions offer dedicated first responder programs with reduced rates, waived fees, or streamlined approvals in recognition of the service these workers provide.",
    amountMin: 1000,
    amountMax: 75000,
    termMin: 12,
    termMax: 84,
    aprMin: 7.49,
    aprMax: 22.99,
    bullets: [
      "Public sector employment provides stable, verifiable income that lenders favor",
      "Many police and fire credit unions offer personal loan rates below 10% APR",
      "First Responder Finance Network connects you to lenders with first responder discounts",
      "Hero home programs (state-specific) sometimes include personal loan components",
      "Union membership often provides access to credit union loans with no-fee options",
    ],
    faqs: [
      { q: "Are there personal loans specifically designed for first responders?", a: "Several programs exist: (1) First Responder Finance - a network of lenders that offer first responder-specific rates and discounts, often 0.25%-1% below standard APRs. (2) Profession-specific credit unions: LAPD Federal Credit Union, Chicago Firefighters Credit Union, Texas Law Enforcement FCU, and hundreds more across the country offer members personal loans at rates typically 7%-15% APR. (3) LightStream's rate-beat program: if you have a strong credit score (700+) and show first responder employment, LightStream will beat any competing offer by 0.10%. (4) Bank of America and Wells Fargo do not have formal first responder programs, but relationship discounts apply to existing customers in any profession." },
      { q: "Can volunteer firefighters qualify for first responder loan programs?", a: "It depends on the program. Volunteer firefighter status (unpaid) may qualify for first responder recognition programs that are designed around public service status rather than income verification. For credit union membership, many fire credit unions accept both career and volunteer firefighters as members. For income-based loan qualification, volunteer firefighters need a separate income source (a regular job) to qualify for a loan, since volunteer work is unpaid. Some paid-per-call or stipend-based volunteer programs may have small qualifying income. Check with your local firefighters credit union about volunteer member eligibility." },
      { q: "Does pension income qualify for a personal loan if I retired from the fire department?", a: "Yes. Pension income from a municipal fire, police, or EMS retirement system is treated as regular income by personal loan lenders under the Equal Credit Opportunity Act. Lenders must consider all income sources without discounting them based on their origin. A retired firefighter with a $4,500/month pension, good credit, and low DTI qualifies for personal loans just as any employed applicant would. Provide documentation of the pension: an award letter, recent benefit statement, or 1099-R. Retired first responders also retain access to profession-specific credit unions in many cases - check your department's retirement benefit package for credit union continuation eligibility." },
    ],
  },
  "construction-workers": {
    slug: "construction-workers",
    h1: "Personal Loans for Construction Workers: Rates & Approval Tips (2026)",
    title: "Personal Loans for Construction Workers (2026): Approval Guide",
    description: "Personal loan options for construction workers dealing with seasonal income, variable pay, and gaps between contracts. Rates from 9.99% APR. Compare lenders that work with trades income.",
    eyebrow: "Construction worker financing",
    intro: "Construction workers face unique loan challenges: seasonal employment, income that varies by project, gaps between contracts, and a mix of W-2 and 1099 work. Understanding how lenders view construction income - and how to document it - is key to getting approved at competitive rates.",
    amountMin: 2000,
    amountMax: 40000,
    termMin: 12,
    termMax: 72,
    aprMin: 9.99,
    aprMax: 32.99,
    bullets: [
      "W-2 construction workers qualify on the same terms as other employees",
      "1099 and self-employed trades workers need 2 years of tax returns",
      "Seasonal employment documented with 2-year earnings history is generally acceptable",
      "Credit unions serving trades unions often have lower rates and more flexible underwriting",
      "Loan amounts up to $40,000 available for qualified borrowers",
    ],
    faqs: [
      { q: "How do lenders view seasonal construction income?", a: "Lenders understand that construction employment is often seasonal, particularly in Northern states where outdoor work slows in winter. For seasonal workers, lenders calculate 'annualized income' by averaging earnings over 12-24 months rather than using the most recent month's pay stub. A worker who earns $80,000 during 9 months of active work is treated as having $6,667/month in income ($80,000 / 12), not as having no income during the winter. Provide your most recent 2 years of W-2s or tax returns to give lenders the full picture. Credit unions affiliated with your union (if applicable) are often most familiar with seasonal construction income patterns." },
      { q: "I work as both W-2 and 1099 on different jobs. How do lenders handle mixed income?", a: "Mixed income (some W-2 from a general contractor, some 1099 for independent project work) is common in construction. Lenders can count both income streams, but the documentation requirements differ. W-2 income: verified with pay stubs and W-2 forms. 1099 income: verified with 1099 forms and Schedule C or Schedule F on your tax return. Because self-employment income is subject to business expenses, lenders typically count only the net profit (after business expenses) from 1099 work, not the gross 1099 amount. If your 1099 work has high reported expenses, the qualifying income may be lower than your actual deposits. A bank statement loan (from some non-QM lenders) may give credit for actual deposits if tax returns understate your income." },
      { q: "Are there credit unions specifically for construction workers?", a: "Yes. Many trades unions operate or partner with credit unions that offer members preferential rates: IBEW Federal Credit Union (electricians), Laborers International Union partnerships with various credit unions, Carpenters Council FCU in some regions, Plumbers and Pipefitters FCU in several states. Non-union construction workers can also join many credit unions based on location, employer, or association membership. Credit union personal loan rates are typically 1%-4% lower than banks and online lenders for comparable credit profiles, and credit unions tend to be more flexible about irregular income documentation." },
    ],
  },
  "freelancers": {
    slug: "freelancers",
    h1: "Personal Loans for Freelancers: Self-Employment Income & 2026 Rates",
    title: "Personal Loans for Freelancers (2026): Self-Employed Approval Guide",
    description: "How freelancers and independent contractors can qualify for personal loans in 2026. Income documentation, lenders that accept 1099 income, rates from 9.99% APR, and tips to improve approval odds.",
    eyebrow: "Freelancer personal loans",
    intro: "Freelancers have more complex loan applications than salaried employees, but personal loans are absolutely accessible to self-employed borrowers. The key is documentation: lenders need to see consistent income over time, typically 2 years of tax returns. With the right preparation, freelancers with strong credit and stable income can qualify for rates comparable to salaried employees.",
    amountMin: 2000,
    amountMax: 50000,
    termMin: 24,
    termMax: 84,
    aprMin: 9.99,
    aprMax: 35.99,
    bullets: [
      "2 years of self-employment tax returns typically required",
      "Net profit (not gross revenue) is the qualifying income amount",
      "Strong credit score (680+) is especially important without employer verification",
      "Bank statement lenders can help if tax returns understate income due to deductions",
      "LightStream, SoFi, and Discover work well with self-employed borrowers with strong credit",
    ],
    faqs: [
      { q: "What income documentation do freelancers need for a personal loan?", a: "Most lenders require: (1) Two years of federal tax returns (1040 with all schedules). The key figure is your net self-employment income from Schedule C, not gross revenue. (2) Two years of 1099 forms from clients. (3) Two to three months of recent bank statements showing deposits consistent with your reported income. (4) A signed CPA letter or self-prepared profit and loss statement (some lenders request this for recent income confirmation). (5) Active business documentation: business license, LLC registration, or client contracts may be requested but are not universal requirements. The more consistent and well-documented your income, the stronger your application." },
      { q: "What if my tax returns show low income due to business deductions?", a: "This is the most common challenge for freelancers. Business deductions (home office, equipment, vehicle mileage, health insurance, retirement contributions) reduce taxable income - which is great for taxes but makes your qualifying income look lower to lenders. Options: (1) Add back certain deductions: some lenders use 'adjusted income' that adds back depreciation and one-time deductions. Ask your lender what adjustments they allow. (2) Bank statement loans: some non-traditional lenders (Angel Oak, Acra Lending, others) use 12-24 months of bank statement deposits as income documentation rather than tax returns. These lenders exist primarily in the mortgage market but some offer personal loans. (3) Use a co-borrower: if you have a spouse or partner with W-2 income, adding them as a co-borrower may let you qualify on their income. (4) Wait and reduce deductions: if you plan to apply for a loan in 18-24 months, strategically reducing deductions in the prior tax year increases your documented income." },
      { q: "Which lenders are most freelancer-friendly for personal loans?", a: "LightStream: excellent rates for 700+ credit scores, accepts self-employment with strong documentation. No origination fee. SoFi: explicitly markets to self-employed borrowers, accepts 1099 income with 2 years of tax returns, offers unemployment protection (career coaching) as a perk. Upgrade: more flexible DTI requirements, accepts a wider range of credit profiles. Upstart: uses education and employment history in underwriting, which may help newer freelancers with thin credit files. LendingClub: joint application option is useful if you want to add a co-borrower. Avoid lenders that require employer contact information or employment verification phone calls - these create friction for self-employed borrowers." },
    ],
  },
};

export const employmentSlugs = Object.keys(employmentTypes);

export function getEmploymentType(slug: string): UseCase | undefined {
  return employmentTypes[slug];
}
